version: '3.5'

services:
#  db-performance:
#    container_name: db-performance
#    build: .
#    image: db-performance
#    ports:
#      - "8080:8080"
#    depends_on:
#      - sql-server-db
#
#  sql-server-db:
#    container_name: sql-server-db
#    build: ./docker/database-mssql
#    restart: always
#    ports:
#      - "1433:1433"
#    environment:
#      SA_PASSWORD: passworD1
#      ACCEPT_EULA: Y
#      MSSQL_DB: dbp
#      MSSQL_USER: dbp
#      MSSQL_PASSWORD: passworD1

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

